[Interface]
# Name = Wireguard-Example.Mobile
PrivateKey = 
Address = 
MTU = 

[Peer]
# Name = Wireguard-Example.Server.01
PublicKey = 
Endpoint = 
AllowedIPs = 0.0.0.0/0
PresharedKey = 
PersistentKeepalive = 25